//! Raw FFI bindings to pjproject (pjsip, pjlib, pjsip-ua).
//!
//! Generated by bindgen from `pjsip_wrapper.h`.
//! These are unsafe C bindings — use `crates/pjsip/` for the safe wrapper.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
